package ru.yanes.data;

import java.util.Objects;
import lombok.Data;

/**
 * A class representing the space between two adjacent teeth.
 * <p>
 * A space can contain up to two toothbrushes: an inner toothbrush and an outer toothbrush.
 * The inner toothbrush is positioned closer to the center of the mouth, while the outer toothbrush is positioned further from the center.
 * If no toothbrush is installed, the corresponding field is {@code null}.
 * <p>
 * A space's availability is determined by the availability of at least one of its teeth.
 * Installing or clearing a toothbrush is only possible for an available space; otherwise,
 * an {@link IllegalStateException} is thrown. Furthermore, installing an inner
 * toothbrush requires that the outer toothbrush be absent (and vice versa) to avoid
 * overlapping two toothbrushes in the same space. * <p>
 * The {@code @Data} annotation from Lombok automatically generates getters and setters for
 * non-final fields, as well as the {@code equals()}, {@code hashCode()}, and {@code toString()} methods.
 * A constructor with parameters for the final fields {@code leftTooth}, {@code rightTooth}, and
 * {@code position} is also generated by Lombok (if the class has no other constructors).
 */
@Data
public class Space {
	/** Left tooth, limiting the gap (unchangeable). */
	private final Tooth leftTooth;
	/** Right tooth that limits the gap (unchangeable). */
	private final Tooth rightTooth;
	/** The position of the space in the general order (index in the {@link Mouth#getSpaces()} array). */
	private final int position;
	/** The internal brush set in the span. May be {@code null} if not set. */
	private Brush innerBrush = null;
	/** The outer brush installed in the gap. May be {@code null} if not installed. */
	private Brush outerBrush = null;


	/**
	 * Checks whether the inner part of the gap is empty (no inner brush installed).
	 *
	 * @return {@code true} if {@link #innerBrush} is {@code null}, otherwise {@code false}
	 */
	public boolean isInnerEmpty() {
		return Objects.isNull(this.innerBrush);
	}

	/**
	 * Checks whether the outer part of the gap is free (no outer brush is installed).
	 *
	 * @return {@code true} if {@link #outerBrush} is {@code null}, otherwise {@code false}
	 */
	public boolean isOuterEmpty() {
		return Objects.isNull(this.outerBrush);
	}

	/**
	 * Checks if a space is accessible. A space is considered accessible if at least one
	 * of its teeth ({@link #leftTooth} or {@link #rightTooth}) is accessible.
	 *
	 * @return {@code true} if the space is accessible for toothbrush placement, otherwise {@code false}
	 */
	public boolean isAvailable() {
		return this.leftTooth.isAvailable() || this.rightTooth.isAvailable();
	}

	/**
	 * Sets the inner brush for the gap.
	 * <p>
	 * Setting is only possible if the gap is available ({@link #isAvailable()} returns {@code true})
	 * and the outer brush is not installed ({@link #isOuterEmpty()} returns {@code true}).
	 * If the same brush is passed that is already set as the inner brush, it is removed
	 * (the value becomes {@code null}).
	 *
	 * @param brush - the brush to set; if {@code null}, the method does not change the state.
	 * @throws IllegalStateException if the gap is unavailable or the outer brush is already installed.
	 */
	public void setInnerBrush(Brush brush) {
		if (this.isAvailable() && this.isOuterEmpty()) {
			if (Objects.equals(this.innerBrush, brush)) {
				this.innerBrush = null;
			} else {
				this.innerBrush = brush;
			}
		} else {
			throw new IllegalStateException("Space is not available");
		}
	}

	/**
	 * Sets the outer brush for the gap.
	 * <p>
	 * Can only be set if the gap is available ({@link #isAvailable()} returns {@code true})
	 * and the inner brush is not set ({@link #isInnerEmpty()} returns {@code true}).
	 * If the same brush is passed that is already set as the outer brush, it is removed
	 * (the value becomes {@code null}).
	 *
	 * @param brush - the brush to set; if {@code null}, the method does not change the state.
	 * @throws IllegalStateException if the gap is unavailable or the inner brush is already set.
	 */
	public void setOuterBrush(Brush brush) {
		if (this.isAvailable() && this.isInnerEmpty()) {
			if (Objects.equals(this.outerBrush, brush)) {
				this.outerBrush = null;
			} else {
				this.outerBrush = brush;
			}
		} else {
			throw new IllegalStateException("Space is not available");
		}
	}

	/**
	 * Removes the inner brush from the span (sets {@link #innerBrush} to {@code null}).
	 *
	 * @throws IllegalStateException if the span is unavailable ({@link #isAvailable()} returns {@code false})
	 */
	public void emptyInnerBrush() {
		if (this.isAvailable()) {
			this.innerBrush = null;
		} else {
			throw new IllegalStateException("Space is not available");
		}
	}

	/**
	 * Removes the outer brush from the span (sets {@link #outerBrush} to {@code null}).
	 *
	 * @throws IllegalStateException if the span is unavailable ({@link #isAvailable()} returns {@code false})
	 */
	public void emptyOuterBrush() {
		if (this.isAvailable()) {
			this.outerBrush = null;
		} else {
			throw new IllegalStateException("Space is not available");
		}
	}
}